name: release:trdl-publish
on:
  push:
    branches:
      - main
    paths:
      - trdl_channels.yaml
  repository_dispatch:
    types: ["release:trdl-publish"]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  publish:
    name: Publish release channels using trdl server
    runs-on: ubuntu-22.04
    steps:
      - name: Notify
        uses: mattermost/action-mattermost-notify@master
        with:
          MATTERMOST_WEBHOOK_URL: ${{ secrets.LOOP_NOTIFICATION_WEBHOOK }}
          MATTERMOST_CHANNEL: ${{ vars.LOOP_NOTIFICATION_CHANNEL }}
          TEXT: |
            ${{ vars.LOOP_NOTIFICATION_GROUP }} [${{ github.workflow }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) nelm task sign pls

      - name: Publish with retry
        uses: werf/trdl-vault-actions/publish@main
        with:
          vault-addr: ${{ secrets.TRDL_VAULT_ADDR }}
          project-name: nelm
          vault-auth-method: approle
          vault-role-id: ${{ secrets.TRDL_VAULT_ROLE_ID }}
          vault-secret-id: ${{ secrets.TRDL_VAULT_SECRET_ID }}

  notify:
    if: always()
    needs:
      - publish
    uses: werf/common-ci/.github/workflows/notification.yml@main
    secrets:
      loopNotificationGroup: ${{ vars.LOOP_NOTIFICATION_GROUP }}
      webhook: ${{ secrets.LOOP_NOTIFICATION_WEBHOOK }}
      notificationChannel: ${{ vars.LOOP_NOTIFICATION_CHANNEL }}
