name: release:release-please
on:
  push:
    branches:
      - "main"
      - "[0-9]+.[0-9]+.[0-9]+*"
      - "[0-9]+.[0-9]+"
      - "[0-9]+"
  repository_dispatch:
    types: ["release:release-please"]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  release-please:
    runs-on: ubuntu-22.04
    steps:
      - name: Extract branch name
        run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Release
        uses: werf/third-party-release-please-action@werf
        with:
          default-branch: ${{ steps.extract_branch.outputs.branch }}
          release-type: go
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          release-notes-header: "## Changelog"
          # FIXME(ilya-lesikov): review, add trdl installation instructions
          release-notes-footer: |
            ## Installation

            Download `nelm` binaries from here:
            * [Linux amd64](https://tuf.nelm.sh/targets/releases/{{> version }}/linux-amd64/bin/nelm) ([PGP signature](https://tuf.nelm.sh/targets/signatures/{{> version }}/linux-amd64/bin/nelm.sig))
            * [Linux arm64](https://tuf.nelm.sh/targets/releases/{{> version }}/linux-arm64/bin/nelm) ([PGP signature](https://tuf.nelm.sh/targets/signatures/{{> version }}/linux-arm64/bin/nelm.sig))
            * [macOS amd64](https://tuf.nelm.sh/targets/releases/{{> version }}/darwin-amd64/bin/nelm) ([PGP signature](https://tuf.nelm.sh/targets/signatures/{{> version }}/darwin-amd64/bin/nelm.sig))
            * [macOS arm64](https://tuf.nelm.sh/targets/releases/{{> version }}/darwin-arm64/bin/nelm) ([PGP signature](https://tuf.nelm.sh/targets/signatures/{{> version }}/darwin-arm64/bin/nelm.sig))
            * [Windows amd64](https://tuf.nelm.sh/targets/releases/{{> version }}/windows-amd64/bin/nelm.exe) ([PGP signature](https://tuf.nelm.sh/targets/signatures/{{> version }}/windows-amd64/bin/nelm.exe.sig))

            These binaries were signed with PGP and could be verified with the [nelm PGP public key](https://raw.githubusercontent.com/werf/nelm/refs/heads/main/pubkey.asc). For example, `nelm` binary can be downloaded and verified with `gpg` on Linux with these commands:
            ```shell
            curl -sSLO "https://tuf.nelm.sh/targets/releases/{{> version }}/linux-amd64/bin/nelm" -O "https://tuf.nelm.sh/targets/signatures/{{> version }}/linux-amd64/bin/nelm.sig"
            curl -sSL https://raw.githubusercontent.com/werf/nelm/refs/heads/main/pubkey.asc | gpg --import
            gpg --verify nelm.sig nelm
            ```

  notify:
    if: failure()
    needs: release-please
    uses: werf/common-ci/.github/workflows/notification.yml@main
    secrets:
      loopNotificationGroup: ${{ secrets.LOOP_NOTIFICATION_GROUP }}
      webhook: ${{ secrets.LOOP_NOTIFICATION_WEBHOOK }}
      notificationChannel: ${{ secrets.LOOP_NOTIFICATION_CHANNEL }}
